# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    # - sudo apt-get install -y upx
builds:
  - id: ehco
    main: ./cmd/ehco/main.go
    flags:
      - -trimpath
    ldflags:
      - -w -s
      - -X github.com/Ehco1996/ehco/internal/constant.GitBranch={{.Branch}}
      - -X github.com/Ehco1996/ehco/internal/constant.GitRevision={{.ShortCommit}}
      - -X github.com/Ehco1996/ehco/internal/constant.BuildTime={{.Date}}
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    goos:
      - linux
archives:
  - format: binary
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
upx:
  - enabled: true
    compress: 9
