{
 "title": "中转节点",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(go_goroutines, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "node exporter basic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic Basic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{job=\"$job\",instance=~\"$instance\"}[$__rate_interval])*8",
       "legendFormat": "recv {{device}}"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{job=\"$job\",instance=~\"$instance\"}[$__rate_interval])*8",
       "legendFormat": "trans {{device}}"
      }
     ]
    },
    {
     "title": "CPU Basic",
     "type": "timeseries",
     "description": "Basic CPU info",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"$job\",instance=~\"$instance\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$job\",instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"$job\",instance=~\"$instance\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$job\",instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"$job\",instance=~\"$instance\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$job\",instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"$job\",instance=~\"$instance\", mode=~\".*irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$job\",instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"$job\",instance=~\"$instance\", mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$job\",instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"$job\",instance=~\"$instance\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$job\",instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "timeseries",
     "description": "Basic memory usage",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=\"$job\",instance=~\"$instance\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{job=\"$job\",instance=~\"$instance\"} - node_memory_MemFree_bytes{job=\"$job\",instance=~\"$instance\"} - (node_memory_Cached_bytes{job=\"$job\",instance=~\"$instance\"} + node_memory_Buffers_bytes{job=\"$job\",instance=~\"$instance\"} + node_memory_SReclaimable_bytes{job=\"$job\",instance=~\"$instance\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{job=\"$job\",instance=~\"$instance\"} + node_memory_Buffers_bytes{job=\"$job\",instance=~\"$instance\"} + node_memory_SReclaimable_bytes{job=\"$job\",instance=~\"$instance\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{job=\"$job\",instance=~\"$instance\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{job=\"$job\",instance=~\"$instance\"} - node_memory_SwapFree_bytes{job=\"$job\",instance=~\"$instance\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Disk Space Used Basic",
     "type": "timeseries",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{job=\"$job\",instance=~\"$instance\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{job=\"$job\",instance=~\"$instance\",device!~'rootfs'})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  { "title": "ehco network metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "中转节点数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(ehco_alive_state)" }
   ]
  },
  {
   "title": "内存",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 2 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (go_memstats_sys_bytes{instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "请求握手时间",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(ehco_traffic_handshake_duration_bucket{job=\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (le,instance,remote))",
     "legendFormat": "{{instance}} - {{remote}}"
    }
   ]
  },
  {
   "title": "流量消耗",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ehco_traffic_network_transmit_bytes{job=\"$job\",instance=~\"$instance\"}) by (instance,remote)",
     "legendFormat": "{{instance}} : {{remote}}"
    }
   ]
  },
  {
   "title": "流量速率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "irate(ehco_traffic_network_transmit_bytes{job=\"$job\",instance=~\"$instance\",flow=\"read\"}[$__rate_interval]) * 8",
     "legendFormat": "{{instance}} - {{remote}}-{{type}}-read"
    },
    {
     "expr": "-irate(ehco_traffic_network_transmit_bytes{job=\"$job\",instance=~\"$instance\",flow=\"write\"}[$__rate_interval]) * 8",
     "legendFormat": "{{instance}} - {{remote}}-{{type}}-write"
    }
   ]
  },
  {
   "title": "实时连接数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ehco_traffic_current_connection_count{job=\"$job\",type=\"tcp\",instance=~\"$instance\"}) by (instance,remote)",
     "legendFormat": "{{instance}} - {{remote}}-tcp"
    },
    {
     "expr": "sum(ehco_traffic_current_connection_count{job=\"$job\",type=\"udp\",instance=~\"$instance\"}) by (instance,remote)",
     "legendFormat": "{{instance}} - {{remote}}-udp"
    }
   ]
  },
  {
   "title": "ehco ping metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ping Total",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ehco_ping_requests_total{}) by (instance)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Ping Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9,sum(rate(ehco_ping_response_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (label,host,le))",
       "legendFormat": "{{label}}-{{host}}"
      }
     ]
    }
   ]
  }
 ]
}