name: go-releaser

on:
  push:
    tags:
      - "*"
    branches:
      - test-ci
  workflow_dispatch:

jobs:
  build-tag-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: set up qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Build multi-platform image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: "ehco1996/ehco:${{ steps.vars.outputs.tag }}"
          push: true
          file: build/Dockerfile
          platforms: linux/amd64,linux/arm64

  go-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.21"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go mod download

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
